package typegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

type RenderOptions struct {
	PackageName    string
	OdooImportPath string
}

func Render(cache MetadataCache, options RenderOptions) ([]byte, error) {
	packageName := options.PackageName
	if packageName == "" {
		packageName = "odoomodels"
	}
	odooImportPath := strings.TrimRight(options.OdooImportPath, "/")
	if odooImportPath == "" {
		odooImportPath = "github.com/TomassiCoffee/odoo-go"
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by odoo-gen. DO NOT EDIT.\n")
	b.WriteString("// Generated from Odoo ir.model and ir.model.fields using JSON-2 search_read.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"sort\"\n\n")
	fmt.Fprintf(&b, "\t\"%s\"\n", odooImportPath)
	b.WriteString(")\n\n")

	modelNames := ModelTypeNames(cache.Models)
	renderRegistry(&b, cache.Models)
	renderAPI(&b, cache.Models, modelNames)
	for _, model := range cache.Models {
		renderModel(&b, model, modelNames[model.Name])
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return b.Bytes(), fmt.Errorf("format generated Go source: %w", err)
	}
	return formatted, nil
}

func renderRegistry(b *bytes.Buffer, models []NormalizedModel) {
	b.WriteString("var Registry = odoo.ModelRegistry{\n")
	for _, model := range models {
		fmt.Fprintf(b, "\t%q: {\n", model.Name)
		for _, field := range model.Fields {
			parts := []string{fmt.Sprintf("Type: %q", field.Type)}
			if field.Label != "" {
				parts = append(parts, fmt.Sprintf("Label: %q", field.Label))
			}
			if field.Relation != "" {
				parts = append(parts, fmt.Sprintf("Relation: %q", field.Relation))
			}
			if field.Required {
				parts = append(parts, "Required: true")
			}
			if field.Readonly {
				parts = append(parts, "Readonly: true")
			}
			fmt.Fprintf(b, "\t\t%q: {%s},\n", field.Name, strings.Join(parts, ", "))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func KnownModels() []string {\n")
	b.WriteString("\tmodels := make([]string, 0, len(Registry))\n")
	b.WriteString("\tfor model := range Registry { models = append(models, model) }\n")
	b.WriteString("\tsort.Strings(models)\n")
	b.WriteString("\treturn models\n")
	b.WriteString("}\n\n")
}

func renderAPI(b *bytes.Buffer, models []NormalizedModel, modelNames map[string]string) {
	b.WriteString("type APIClient interface {\n")
	b.WriteString("\todoo.RawSearchReader\n\todoo.RawWriter\n")
	b.WriteString("}\n\n")
	b.WriteString("type API struct {\n")
	b.WriteString("\tclient APIClient\n")
	b.WriteString("}\n\n")
	b.WriteString("func NewAPI(client APIClient) *API {\n")
	b.WriteString("\treturn &API{client: client}\n")
	b.WriteString("}\n\n")

	for _, model := range models {
		name := modelNames[model.Name]
		fmt.Fprintf(b, "func (a *API) SearchRead%s(ctx context.Context, options odoo.SearchReadOptions) ([]%s, error) {\n", name, name)
		fmt.Fprintf(b, "\treturn odoo.SearchReadTyped[%s](ctx, a.client, %sModel{}, options)\n", name, name)
		b.WriteString("}\n\n")

		fmt.Fprintf(b, "func (a *API) Write%s(ctx context.Context, ids []odoo.ID, vals %sWrite) (bool, error) {\n", name, name)
		fmt.Fprintf(b, "\treturn odoo.WriteTyped[%s](ctx, a.client, %sModel{}, ids, vals)\n", name, name)
		b.WriteString("}\n\n")
	}
}

func renderModel(b *bytes.Buffer, model NormalizedModel, typeName string) {
	fieldNames := FieldGoNames(model.Fields)
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	for _, field := range model.Fields {
		fmt.Fprintf(b, "\t%s %s `json:%q odoo:%q`\n", fieldNames[field.Name], readGoType(field.Type), field.Name+",omitempty", field.Name)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "type %sWrite struct {\n", typeName)
	for _, field := range model.Fields {
		fmt.Fprintf(b, "\t%s %s `json:%q odoo:%q`\n", fieldNames[field.Name], readWriteGoType(field.Type), field.Name+",omitempty", field.Name)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "type %sModel struct{}\n\n", typeName)
	fmt.Fprintf(b, "func (%sModel) Name() string { return %q }\n\n", typeName, model.Name)
	fmt.Fprintf(b, "func (%sModel) Fields() []string {\n", typeName)
	b.WriteString("\treturn []string{\n")
	for _, field := range model.Fields {
		fmt.Fprintf(b, "\t\t%q,\n", field.Name)
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "func SearchRead%s(ctx context.Context, client APIClient, options odoo.SearchReadOptions) ([]%s, error) {\n", typeName, typeName)
	fmt.Fprintf(b, "\treturn odoo.SearchReadTyped[%s](ctx, client, %sModel{}, options)\n", typeName, typeName)
	b.WriteString("}\n\n")
}

func readGoType(fieldType SupportedFieldType) string {
	switch fieldType {
	case FieldBinary, FieldChar, FieldDate, FieldDatetime, FieldHTML, FieldSelection, FieldText:
		return "odoo.FalseString"
	case FieldBoolean:
		return "bool"
	case FieldFloat:
		return "float64"
	case FieldMonetary:
		return "odoo.Monetary"
	case FieldInteger:
		return "int64"
	case FieldMany2One:
		return "odoo.Many2One"
	case FieldOne2Many, FieldMany2Many:
		return "[]odoo.ID"
	default:
		return "any"
	}
}

func readWriteGoType(fieldType SupportedFieldType) string {
	switch fieldType {
	case FieldBinary, FieldChar, FieldDate, FieldDatetime, FieldHTML, FieldSelection, FieldText:
		return "*odoo.FalseString"
	case FieldBoolean:
		return "*bool"
	case FieldFloat:
		return "*float64"
	case FieldMonetary:
		return "*odoo.Monetary"
	case FieldInteger:
		return "*int64"
	case FieldMany2One:
		return "*odoo.Many2OneWrite"
	case FieldOne2Many:
		return "[]odoo.Many2ManyCommand"
	case FieldMany2Many:
		return "[]odoo.One2ManyCommand"
	default:
		return "any"
	}
}

func SaveCacheJSON(cache MetadataCache) ([]byte, error) {
	return json.MarshalIndent(cache, "", "  ")
}

func SortModels(models []NormalizedModel) {
	sort.Slice(models, func(i, j int) bool { return models[i].Name < models[j].Name })
}
