package typegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

type RenderOptions struct {
	PackageName    string
	OdooImportPath string
}

type Content struct {
	Content bytes.Buffer
}

type GeneratedFile map[string]Content
type ResultFile map[string]([]byte)

func Render(cache MetadataCache, options RenderOptions) (ResultFile, error) {
	packageName := options.PackageName
	if packageName == "" {
		packageName = "odoomodels"
	}
	odooImportPath := strings.TrimRight(options.OdooImportPath, "/")
	if odooImportPath == "" {
		odooImportPath = "github.com/TomassiCoffee/odoo-go"
	}

	modelNames := ModelTypeNames(cache.Models)

	genFiles := GeneratedFile{}
	registry := Content{}

	renderRegistryHeader(&registry.Content, packageName, odooImportPath)
	renderRegistry(&registry.Content, cache.Models)
	renderAPI(&registry.Content, cache.Models, modelNames)
	genFiles["registry"] = registry

	for _, model := range cache.Models {
		modelContent := Content{}
		name := modelNames[model.Name]

		renderModelHeader(&modelContent.Content, packageName, odooImportPath)
		renderModel(&modelContent.Content, model, name)

		genFiles[model.Name] = modelContent
	}

	resultFiles := ResultFile{}
	for name, genFile := range genFiles {
		bytesFile := genFile.Content.Bytes()
		formatted, err := format.Source(bytesFile)
		if err != nil {
			resultFiles[name] = bytesFile
			fmt.Errorf("format generated Go source: %s%w", name, err)
		}else {
			resultFiles[name] = formatted
		}
	}
	return resultFiles, nil
}

func renderModelHeader(b *bytes.Buffer, packageName string, odooImportPath string) {
	b.WriteString("// Code generated by odoo-gen. DO NOT EDIT.\n")
	b.WriteString("// Generated from Odoo ir.model and ir.model.fields using JSON-2 search_read.\n\n")
	fmt.Fprintf(b, "package %s\n\n", packageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"context\"\n")
	fmt.Fprintf(b, "\t\"%s\"\n", odooImportPath)
	b.WriteString(")\n\n")
	b.WriteString("var _ = fmt.Errorf\n\n")
}

func renderRegistryHeader(b *bytes.Buffer, packageName string, odooImportPath string) {
	b.WriteString("// Code generated by odoo-gen. DO NOT EDIT.\n")
	b.WriteString("// Generated from Odoo ir.model and ir.model.fields using JSON-2 search_read.\n\n")
	fmt.Fprintf(b, "package %s\n\n", packageName)
	b.WriteString("import (\n")
	b.WriteString("\t\"sort\"\n\n")
	fmt.Fprintf(b, "\t\"%s\"\n", odooImportPath)
	b.WriteString(")\n\n")
}

func renderRegistry(b *bytes.Buffer, models []NormalizedModel) {
	b.WriteString("var Registry = odoo.ModelRegistry{\n")
	for _, model := range models {
		fmt.Fprintf(b, "\t%q: {\n", model.Name)
		for _, field := range model.Fields {
			parts := []string{fmt.Sprintf("Type: %q", field.Type)}
			if field.Label != "" {
				parts = append(parts, fmt.Sprintf("Label: %q", field.Label))
			}
			if field.Relation != "" {
				parts = append(parts, fmt.Sprintf("Relation: %q", field.Relation))
			}
			if field.Required {
				parts = append(parts, "Required: true")
			}
			if field.Readonly {
				parts = append(parts, "Readonly: true")
			}
			fmt.Fprintf(b, "\t\t%q: {%s},\n", field.Name, strings.Join(parts, ", "))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func KnownModels() []string {\n")
	b.WriteString("\tmodels := make([]string, 0, len(Registry))\n")
	b.WriteString("\tfor model := range Registry { models = append(models, model) }\n")
	b.WriteString("\tsort.Strings(models)\n")
	b.WriteString("\treturn models\n")
	b.WriteString("}\n\n")
}

func renderAPI(b *bytes.Buffer, models []NormalizedModel, modelNames map[string]string) {
	b.WriteString("type APIClient interface {\n")
	b.WriteString("\todoo.Caller\n")
	b.WriteString("}\n\n")
	b.WriteString("type API struct {\n")
	b.WriteString("\tclient APIClient\n")
	b.WriteString("}\n\n")
	b.WriteString("func NewAPI(client APIClient) *API {\n")
	b.WriteString("\treturn &API{client: client}\n")
	b.WriteString("}\n\n")
}

func renderModel(b *bytes.Buffer, model NormalizedModel, typeName string) {
	fieldNames := FieldGoNames(model.Fields)
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	for _, field := range model.Fields {
		fmt.Fprintf(
			b,
			"\t%s %s `json:%q odoo:%q`\n",
			fieldNames[field.Name],
			readGoType(field.Type),
			field.Name+",omitempty",
			field.Name,
		)
	}
	b.WriteString("}\n\n")

	writeCreateStruct(b, typeName, model)
	writeCreateBuilder(b, typeName, model)

	writeWriteStruct(b, typeName, model)
	writeWriteBuilder(b, typeName, model)

	fmt.Fprintf(b, "type %sModel struct{}\n\n", typeName)
	fmt.Fprintf(b, "func (%sModel) RecordType() *%s { return nil; }\n\n", typeName, typeName)
	fmt.Fprintf(b, "func (%sModel) Name() string { return %q; }\n\n", typeName, model.Name)
	fmt.Fprintf(b, "func (%sModel) Fields() []string {\n", typeName)
	b.WriteString("\treturn []string{\n")
	for _, field := range model.Fields {
		fmt.Fprintf(b, "\t\t%q,\n", field.Name)
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	renderMethodsAPICall(b, model, typeName)
}

func builderInputType(
	fieldType SupportedFieldType,
	storageType string,
) string {
	switch fieldType {
	case FieldBinary,
		FieldChar,
		FieldDate,
		FieldDatetime,
		FieldHTML,
		FieldSelection,
		FieldText,
		FieldMonetary:
		return "string"

	default:
		return strings.TrimPrefix(storageType, "*")
	}
}

func writeBuilderSetter(
	b *bytes.Buffer,
	builderType string,
	field NormalizedField,
	goName string,
	storageType string,
) {
	inputType := builderInputType(field.Type, storageType)

	fmt.Fprintf(
		b,
		"func (b *%s) With%s(value %s) *%s {\n",
		builderType,
		goName,
		inputType,
		builderType,
	)

	switch field.Type {
	case FieldBinary,
		FieldChar,
		FieldDate,
		FieldDatetime,
		FieldHTML,
		FieldSelection,
		FieldText:

		b.WriteString("\tv := odoo.NewFalseString(value)\n")

		if strings.HasPrefix(storageType, "*") {
			fmt.Fprintf(
				b,
				"\tb.value.%s = &v\n",
				goName,
			)
		} else {
			fmt.Fprintf(
				b,
				"\tb.value.%s = v\n",
				goName,
			)
		}

	case FieldMonetary:
		b.WriteString("\tv, err := odoo.NewMonetary(value)\n")
		b.WriteString("\tif err != nil {\n")
		fmt.Fprintf(b, "\t\tb.err = errors.Join(b.err, fmt.Errorf(\"tip_amount: %%w\", err))\n")
		b.WriteString("\t\treturn b\n")
		b.WriteString("\t}\n")

		if strings.HasPrefix(storageType, "*") {
			fmt.Fprintf(
				b,
				"\tb.value.%s = &v\n",
				goName,
			)
		} else {
			fmt.Fprintf(
				b,
				"\tb.value.%s = v\n",
				goName,
			)
		}

	default:
		if strings.HasPrefix(storageType, "*") {
			fmt.Fprintf(
				b,
				"\tb.value.%s = &value\n",
				goName,
			)
		} else {
			fmt.Fprintf(
				b,
				"\tb.value.%s = value\n",
				goName,
			)
		}
	}

	b.WriteString("\treturn b\n")
	b.WriteString("}\n\n")
}


func writeCreateStruct(
	b *bytes.Buffer,
	typeName string,
	model NormalizedModel,
) {
	fieldNames := FieldGoNames(model.Fields)

	fmt.Fprintf(
		b,
		"type %s_Create struct {\n",
		typeName,
	)

	for _, field := range model.Fields {
		jsonName := field.Name

		if !field.Required {
			jsonName += ",omitempty"
		}

		fmt.Fprintf(
			b,
			"\t%s %s `json:%q odoo:%q`\n",
			fieldNames[field.Name],
			createGoType(field),
			jsonName,
			field.Name,
		)
	}

	b.WriteString("}\n\n")
}


func writeWriteStruct(
	b *bytes.Buffer,
	typeName string,
	model NormalizedModel,
) {
	fieldNames := FieldGoNames(model.Fields)

	fmt.Fprintf(
		b,
		"type %s_Write struct {\n",
		typeName,
	)

	for _, field := range model.Fields {
		fmt.Fprintf(
			b,
			"\t%s %s `json:%q odoo:%q`\n",
			fieldNames[field.Name],
			readWriteGoType(field.Type),
			field.Name+",omitempty",
			field.Name,
		)
	}

	b.WriteString("}\n\n")
}


func writeCreateBuilder(
	b *bytes.Buffer,
	typeName string,
	model NormalizedModel,
) {
	fieldNames := FieldGoNames(model.Fields)
	builderType := typeName + "CreateBuilder"

	// Builder storage.
	fmt.Fprintf(
		b,
		"type %s struct {\n"+
			"\tvalue %s_Create\n"+
			"\terr error\n"+
			"}\n\n",
		builderType,
		typeName,
	)

	// Constructor.
	//
	// Every Odoo-required field becomes a required Go constructor argument.
	fmt.Fprintf(
		b,
		"func New%s(\n",
		builderType,
	)

	for _, field := range model.Fields {
		if !field.Required {
			continue
		}

		goName := fieldNames[field.Name]
		storageType := createGoType(field)

		fmt.Fprintf(
			b,
			"\tv%s %s,\n",
			goName,
			builderInputType(field.Type, storageType),
		)
	}

	fmt.Fprintf(
		b,
		") *%s {\n",
		builderType,
	)

	fmt.Fprintf(
		b,
		"\tb := &%s{value: %s_Create{}}\n",
		builderType,
		typeName,
	)

	// Convert / assign required constructor fields.
	for _, field := range model.Fields {
		if !field.Required {
			continue
		}

		goName := fieldNames[field.Name]

		switch field.Type {
		case FieldBinary,
			FieldChar,
			FieldDate,
			FieldDatetime,
			FieldHTML,
			FieldSelection,
			FieldText:

			fmt.Fprintf(
				b,
				"\tb.value.%s = odoo.NewFalseString(v%s)\n",
				goName,
				goName,
			)

		case FieldMonetary:
			localName := "value" + goName

			fmt.Fprintf(
				b,
				"\t%s, err := odoo.NewMonetary(v%s)\n",
				localName,
				goName,
			)

			b.WriteString("\tif err != nil {\n")
			fmt.Fprintf(b, "b.err = errors.Join(b.err, fmt.Errorf(\"tip_amount: %%w\", err))")
			b.WriteString("\t} else {\n")

			fmt.Fprintf(
				b,
				"\t\tb.value.%s = %s\n",
				goName,
				localName,
			)

			b.WriteString("\t}\n")

		default:
			fmt.Fprintf(
				b,
				"\tb.value.%s = v%s\n",
				goName,
				goName,
			)
		}
	}

	b.WriteString("\treturn b\n")
	b.WriteString("}\n\n")

	// Optional create setters only.
	for _, field := range model.Fields {
		if field.Required {
			continue
		}

		goName := fieldNames[field.Name]

		writeBuilderSetter(
			b,
			builderType,
			field,
			goName,
			createGoType(field),
		)
	}

	// Build.
	fmt.Fprintf(
		b,
		"func (b *%s) Build() (%s_Create, error) {\n",
		builderType,
		typeName,
	)

	b.WriteString("\tif b.err != nil {\n")

	fmt.Fprintf(
		b,
		"\t\treturn %s_Create{}, b.err\n",
		typeName,
	)

	b.WriteString("\t}\n")
	b.WriteString("\treturn b.value, nil\n")
	b.WriteString("}\n\n")
}

func writeWriteBuilder(
	b *bytes.Buffer,
	typeName string,
	model NormalizedModel,
) {
	fieldNames := FieldGoNames(model.Fields)
	builderType := typeName + "WriteBuilder"

	fmt.Fprintf(
		b,
		"type %s struct {\n"+
			"\tvalue %s_Write\n"+
			"\terr error\n"+
			"}\n\n",
		builderType,
		typeName,
	)

	fmt.Fprintf(
		b,
		"func New%[1]sWriteBuilder() *%[1]sWriteBuilder {\n"+
			"\treturn &%[1]sWriteBuilder{\n"+
			"\t\tvalue: %[1]s_Write{},\n"+
			"\t}\n"+
			"}\n\n",
		typeName,
	)

	// Generate setters for EVERY writable field.
	//
	// Odoo's `required` flag is a create/model constraint. During write(),
	// even a required model field is optional in the request because the caller
	// may choose not to modify it.
	for _, field := range model.Fields {
		goName := fieldNames[field.Name]

		writeBuilderSetter(
			b,
			builderType,
			field,
			goName,
			readWriteGoType(field.Type),
		)
	}

	fmt.Fprintf(
		b,
		"func (b *%s) Build() (%s_Write, error) {\n",
		builderType,
		typeName,
	)

	b.WriteString("\tif b.err != nil {\n")

	fmt.Fprintf(
		b,
		"\t\treturn %s_Write{}, b.err\n",
		typeName,
	)

	b.WriteString("\t}\n")
	b.WriteString("\treturn b.value, nil\n")
	b.WriteString("}\n\n")
}

func renderMethodsAPICall(b *bytes.Buffer, model NormalizedModel, typeName string) {
	type method struct {
		name     string
		args     string
		result   string
		call     string
		callArgs string
	}

	methods := []method{
		{"SearchRead", "options odoo.SearchReadOptions", "([]$T, error)", "SearchReadTyped", "options"},
		{"Search", "options odoo.SearchOptions", "([]odoo.ID, error)", "SearchTyped", "options"},
		{"Read", "options odoo.ReadOptions", "([]$T, error)", "ReadTyped", "options"},

		{"Create", "vals []$T_Create", "([]odoo.ID, error)", "CreateTyped", "vals"},
		{"Write", "ids []odoo.ID, vals $T_Write", "(bool, error)", "WriteTyped", "ids, vals"},
		{"Unlink", "ids []odoo.ID", "(bool, error)", "UnlinkTyped", "ids"},

		{"ActionArchive", "ids []odoo.ID", "error", "ActionArchiveTyped", "ids"},
		{"ActionUnarchive", "ids []odoo.ID", "error", "ActionUnarchiveTyped", "ids"},

		{"CheckFieldAccess", "options odoo.CheckFieldAccessOptions", "error", "CheckFieldAccessTyped", "options"},
		{"Copy", "options odoo.CopyOptions", "([]odoo.ID, error)", "CopyTyped", "options"},
		{"CopyData", "options odoo.CopyDataOptions", "([]$T, error)", "CopyDataTyped", "options"},
		// {"CopyTranslations", "options odoo.CopyTranslationsOptions", "error", "CopyTranslationsTyped", "options"},
		{"DefaultGet", "options odoo.DefaultGetOptions", "(odoo.Values, error)", "DefaultGetTyped", "options"},
		{"ExportData", "options odoo.ExportDataOptions", "(odoo.ExportDataResult, error)", "ExportDataTyped", "options"},
		{"FieldsGet", "options odoo.FieldsGetOptions", "(map[string]odoo.FieldDefinition, error)", "FieldsGetTyped", "options"},

		{"GetBaseURL", "ids []odoo.ID", "(string, error)", "GetBaseURLTyped", "ids"},
		{"GetExternalID", "ids []odoo.ID", "(map[odoo.ID]string, error)", "GetExternalIDTyped", "ids"},
		{"GetFieldTranslations", "options odoo.GetFieldTranslationsOptions", "(odoo.FieldTranslationsResult, error)", "GetFieldTranslationsTyped", "options"},
		{"GetMetadata", "ids []odoo.ID", "([]odoo.Metadata, error)", "GetMetadataTyped", "ids"},
		{"GetPropertyDefinition", "options odoo.GetPropertyDefinitionOptions", "(odoo.Values, error)", "GetPropertyDefinitionTyped", "options"},

		{"HasAccess", "options odoo.HasAccessOptions", "(bool, error)", "HasAccessTyped", "options"},
		{"HasFieldAccess", "options odoo.HasFieldAccessOptions", "(bool, error)", "HasFieldAccessTyped", "options"},
		{"Load", "options odoo.LoadOptions", "(odoo.LoadResult, error)", "LoadTyped", "options"},
		{"NameCreate", "options odoo.NameCreateOptions", "(*odoo.NamePair, error)", "NameCreateTyped", "options"},
		{"NameSearch", "options odoo.NameSearchOptions", "([]odoo.NamePair, error)", "NameSearchTyped", "options"},
		{"Onchange", "options odoo.OnchangeOptions", "(odoo.Values, error)", "OnchangeTyped", "options"},
		{"SearchCount", "options odoo.SearchCountOptions", "(int, error)", "SearchCountTyped", "options"},
		{"UpdateFieldTranslations", "options odoo.UpdateFieldTranslationsOptions", "(bool, error)", "UpdateFieldTranslationsTyped", "options"},
	}

	expand := func(s string) string {
		return strings.ReplaceAll(s, "$T", typeName)
	}

	for _, m := range methods {
		fmt.Fprintf(b, "func (a *API) %s%s(ctx context.Context, %s) %s { return odoo.%s(ctx, a.client, %sModel{}, %s); }\n",
			m.name,
			typeName,
			expand(m.args),
			expand(m.result),
			m.call,
			typeName,
			m.callArgs,
		)
	}
}

func readGoType(fieldType SupportedFieldType) string {
	switch fieldType {
	case FieldBinary,
		FieldChar,
		FieldDate,
		FieldDatetime,
		FieldHTML,
		FieldSelection,
		FieldText:
		return "odoo.FalseString"

	case FieldBoolean:
		return "bool"

	case FieldFloat:
		return "float64"

	case FieldMonetary:
		return "odoo.Monetary"

	case FieldInteger:
		return "int64"

	case FieldMany2One:
		return "odoo.Many2One"

	case FieldOne2Many, FieldMany2Many:
		return "[]odoo.ID"

	default:
		return "any"
	}
}

func readWriteGoType(fieldType SupportedFieldType) string {
	switch fieldType {
	case FieldBinary,
		FieldChar,
		FieldDate,
		FieldDatetime,
		FieldHTML,
		FieldSelection,
		FieldText:
		return "*odoo.FalseString"

	case FieldBoolean:
		return "*bool"

	case FieldFloat:
		return "*float64"

	case FieldMonetary:
		return "*odoo.Monetary"

	case FieldInteger:
		return "*int64"

	case FieldMany2One:
		return "*odoo.Many2OneWrite"

	case FieldOne2Many:
		return "[]odoo.One2ManyCommand"

	case FieldMany2Many:
		return "[]odoo.Many2ManyCommand"

	default:
		return "any"
	}
}

// Required create fields must always be present, therefore they use the concrete
// read representation. Optional create fields use the write representation so
// nil means "not supplied".
func createGoType(field NormalizedField) string {
	if field.Required {
		return readGoType(field.Type)
	}

	return readWriteGoType(field.Type)
}

func SaveCacheJSON(cache MetadataCache) ([]byte, error) {
	return json.MarshalIndent(cache, "", "  ")
}

func SortModels(models []NormalizedModel) {
	sort.Slice(models, func(i, j int) bool { return models[i].Name < models[j].Name })
}
